/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.bigtranslate.workflow;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

/**
 * The failure this guards against is a Workflow Manager that reports itself
 * completely healthy while being unable to start a single workflow: it binds
 * its port, loads its policy and registers its events, so every health check
 * passes, and every instance then fails against a table that is not there.
 */
public class TestWorkflowInstanceSchema {

  @Rule
  public TemporaryFolder folder = new TemporaryFolder();

  private File sql;

  @Before
  public void setUp() throws Exception {
    sql = new File(folder.getRoot(), "workflow-instances.sql");
    write(sql,
        "-- a comment, which is not a statement",
        "CREATE TABLE workflow_instances (",
        "  workflow_instance_id INTEGER GENERATED BY DEFAULT AS IDENTITY",
        "    (START WITH 1) NOT NULL PRIMARY KEY,",
        "  workflow_instance_status VARCHAR(255),",
        "  workflow_id VARCHAR(255) NOT NULL,",
        "  current_task_id VARCHAR(255) NOT NULL",
        ");",
        "",
        "CREATE TABLE workflow_instance_metadata (",
        "  workflow_instance_id INTEGER NOT NULL,",
        "  workflow_met_key VARCHAR(1000) NOT NULL,",
        "  workflow_met_val VARCHAR(1000) NOT NULL",
        ");",
        "-- a trailing comment after the last semicolon");
  }

  @Test
  public void createsTheTablesWhenTheDatabaseIsEmpty() throws Exception {
    File properties = properties(url("empty"));
    assertTrue(WorkflowInstanceSchema.ensure(properties, sql));
    assertTrue(tableExists("empty", "workflow_instances"));
    assertTrue(tableExists("empty", "workflow_instance_metadata"));
  }

  /**
   * Run on every start, so it has to be safe to run against a database that
   * is already there and full of a run's history.
   */
  @Test
  public void leavesAnExistingDatabaseAlone() throws Exception {
    File properties = properties(url("existing"));
    assertTrue(WorkflowInstanceSchema.ensure(properties, sql));

    Connection connection = connect("existing");
    try {
      Statement statement = connection.createStatement();
      statement.execute("INSERT INTO workflow_instances "
          + "(workflow_instance_status, workflow_id, current_task_id) "
          + "VALUES ('Queued', 'urn:w', 'urn:t')");
      statement.close();
    } finally {
      shutdown(connection);
    }

    assertTrue(WorkflowInstanceSchema.ensure(properties, sql));
    assertEquals("the run's history must survive a restart",
        1, rowCount("existing"));
  }

  @Test
  public void doesNothingForALuceneBackedRepository() throws Exception {
    File properties = folder.newFile("lucene.properties");
    write(properties,
        "workflow.engine.instanceRep.factory = org.apache.oodt.cas.workflow."
            + "instrepo.LuceneWorkflowInstanceRepositoryFactory");
    assertTrue(WorkflowInstanceSchema.ensure(properties, sql));
  }

  @Test
  public void reportsFailureWhenTheUrlIsMissing() throws Exception {
    File properties = folder.newFile("nourl.properties");
    write(properties, "workflow.engine.instanceRep.factory = "
        + WorkflowInstanceSchema.DATASOURCE_FACTORY);
    assertFalse("a datasource repository with no url is a broken config",
        WorkflowInstanceSchema.ensure(properties, sql));
  }

  /**
   * The url in workflow.properties is written with the same {@code [NAME]}
   * placeholders as the rest of the OODT policy.
   */
  @Test
  public void resolvesPlaceholdersFromTheEnvironment() throws Exception {
    String home = System.getenv("HOME");
    assertTrue("this test needs HOME set", home != null && home.length() > 0);
    assertEquals(home + "/data/winstdb/winst",
        WorkflowInstanceSchema.resolve("[HOME]/data/winstdb/winst"));
  }

  @Test
  public void leavesAnUnsetPlaceholderAsItIs() throws Exception {
    assertEquals("[NOT_A_REAL_VARIABLE_ANYWHERE]/x",
        WorkflowInstanceSchema.resolve("[NOT_A_REAL_VARIABLE_ANYWHERE]/x"));
  }

  /**
   * An unresolved placeholder is not a path, and carrying on with one is
   * worse than stopping. HSQLDB opens
   * {@code jdbc:hsqldb:file:[OODT_HOME]/data/winstdb/winst} without
   * complaint, creating a directory called "[OODT_HOME]" next to wherever
   * the process was started, and the run that follows finds an empty
   * data/winstdb behind a message saying the tables were created.
   */
  @Test
  public void refusesAUrlWithAnUnresolvedPlaceholder() throws Exception {
    File properties = properties(
        "jdbc:hsqldb:file:[NOT_A_REAL_VARIABLE_ANYWHERE]/data/winstdb/winst");
    assertFalse("a url with a placeholder nothing answers is not a database",
        WorkflowInstanceSchema.ensure(properties, sql));
    assertFalse("it created the database under the literal placeholder",
        new File("[NOT_A_REAL_VARIABLE_ANYWHERE]").exists());
  }

  @Test
  public void doesNotTakeATrailingCommentForAStatement() throws Exception {
    List<String> statements = WorkflowInstanceSchema.statements(sql);
    assertEquals(2, statements.size());
    for (String each : statements) {
      assertFalse(each.trim().isEmpty());
    }
  }

  // ------------------------------------------------------------- helpers ---

  private String url(String name) {
    return "jdbc:hsqldb:file:"
        + new File(folder.getRoot(), name + "/db").getAbsolutePath();
  }

  private File properties(String jdbcUrl) throws Exception {
    File file = folder.newFile(
        "workflow-" + Math.abs(jdbcUrl.hashCode()) + ".properties");
    write(file,
        "workflow.engine.instanceRep.factory = "
            + WorkflowInstanceSchema.DATASOURCE_FACTORY,
        WorkflowInstanceSchema.URL_KEY + "=" + jdbcUrl,
        WorkflowInstanceSchema.USER_KEY + "=sa",
        WorkflowInstanceSchema.PASS_KEY + "=",
        WorkflowInstanceSchema.DRIVER_KEY + "=org.hsqldb.jdbc.JDBCDriver");
    return file;
  }

  private Connection connect(String name) throws Exception {
    return DriverManager.getConnection(url(name), "sa", "");
  }

  private boolean tableExists(String name, String table) throws Exception {
    Connection connection = connect(name);
    try {
      return WorkflowInstanceSchema.hasTable(connection, table);
    } finally {
      shutdown(connection);
    }
  }

  private int rowCount(String name) throws Exception {
    Connection connection = connect(name);
    try {
      Statement statement = connection.createStatement();
      try {
        ResultSet results = statement.executeQuery(
            "SELECT COUNT(*) FROM workflow_instances");
        results.next();
        return results.getInt(1);
      } finally {
        statement.close();
      }
    } finally {
      shutdown(connection);
    }
  }

  private void shutdown(Connection connection) throws Exception {
    Statement statement = connection.createStatement();
    try {
      statement.execute("SHUTDOWN");
    } finally {
      statement.close();
      connection.close();
    }
  }

  private void write(File file, String... lines) throws Exception {
    Writer writer = new OutputStreamWriter(new FileOutputStream(file),
        StandardCharsets.UTF_8);
    try {
      for (String line : lines) {
        writer.write(line);
        writer.write("\n");
      }
    } finally {
      writer.close();
    }
  }
}
